apiVersion: v1
kind: Service
metadata:
  name: {{ include "thor-daemon.fullname" . }}
  labels:
    {{- include "thor-daemon.labels" . | nindent 4 }}
  annotations:
    # AWS
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # hcloud
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/disable-private-ingress: "true"
spec:
  type: {{ .Values.service.type }}
  {{- if ne "ClusterIP" .Values.service.type }}
  externalTrafficPolicy: Local
  {{- end }}
  ports:
    - name: p2p
      port: {{ include "thor-daemon.p2p" . }}
      targetPort: p2p
      protocol: TCP
    - name: rpc
      port: {{ include "thor-daemon.rpc" . }}
      targetPort: rpc
      protocol: TCP
    - name: prometheus
      port: 26660
      targetPort: prometheus
      protocol: TCP
  selector:
    {{- include "thor-daemon.selectorLabels" . | nindent 4 }}
